export const WEBSITES_AND_APPS = [
  {
    id: "portfolio",
    title: "Developer Portfolio",
    description:
      "Personal portfolio website built with modern web technologies",
    imageUrl: "/tech-logos/daisyui.svg",
    techStacks: ["astro", "react", "tailwind", "typescript"],
    demoUrl: "https://portfolio.example.com",
    githubUrl: "https://github.com/example/portfolio",
  },
  {
    id: "ecommerce",
    title: "E-commerce Platform",
    description: "Full-featured online shop with payment processing",
    imageUrl: "/tech-logos/daisyui.svg",
    techStacks: ["next-js", "typescript", "mongodb", "redux-toolkit"],
    demoUrl: "https://shop.example.com",
    githubUrl: "https://github.com/example/ecommerce",
  },
  {
    id: "blog-platform",
    title: "Content Management System",
    description: "Dynamic blog platform with admin dashboard",
    imageUrl: "/tech-logos/daisyui.svg",
    techStacks: ["react", "node-js", "express", "mysql"],
    demoUrl: "https://blog.example.com",
    githubUrl: "https://github.com/example/blog-platform",
  },
  {
    id: "dashboard",
    title: "Analytics Dashboard",
    description: "Interactive data visualization application",
    imageUrl: "/tech-logos/daisyui.svg",
    techStacks: ["react", "typescript", "tanstack-query", "shadcn"],
    demoUrl: "https://dashboard.example.com",
    githubUrl: "https://github.com/example/dashboard",
  },
  {
    id: "ai-project",
    title: "ML Image Classifier",
    description: "Machine learning application for image recognition",
    imageUrl: "/tech-logos/daisyui.svg",
    techStacks: ["python", "pytorch", "next-js", "tailwind"],
    demoUrl: "https://ai.example.com",
    githubUrl: "https://github.com/example/ai-project",
  },
];
